# Generated by Django 4.2.10 on 2024-02-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='address',
        ),
        migrations.RemoveField(
            model_name='data',
            name='image',
        ),
        migrations.RemoveField(
            model_name='data',
            name='phone',
        ),
    ]
